### PR TITLE
small addition of tags and categories + home page

### PR DESCRIPTION
**Pull request by achauvinhameau**
add loc for the home page with current date and tags/categories if configured in the _config.xml

### CODE REVIEW

**Comment by NoahDragon** [comment]
Could you please make the travis ci happier? 😄

**Comment by achauvinhameau** [comment]
the failling test in travis is linked to a change I've made for the root url (adding date). Let you check wether you want to keep it.

**Comment by NoahDragon** [comment]
I see. Could you please also fix the test file and add test cases for your changes? This will make the future development easier. 😄

**Comment by NoahDragon** [comment]
Thank you. LGTM.

**Comment by h404bi** [comment]
Are there any changes required to make this be merged?

**Comment by tomap** [comment]
LGTM too

**Comment by geektutu** [comment]
Adding loc for the home page is nice,  is there anyone who would click merge button ?

**Comment by mattlin4567** [comment]
什麼時候才能增加 tags 和 category 啊

**Comment by curbengh** [comment]
Rebased.

**Comment by SukkaW** [comment]
@curbengh Ops. Seems that it needs to be rebased again.

**Comment by curbengh** [comment]
Rebased. Updated `sNow` to be date only.

**Comment by SukkaW** [comment]
Approved.

**Pull request merged**
