### PR TITLE
Allow to specify custom template for the sitemap in _config.yml

### PR DESCRIPTION
**Pull request by jimmyn**

### CODE REVIEW

**Comment by NoahDragon** [comment]
Could you please fix the test error?

**Comment by jimmyn** [comment]
@NoahDragon I've fixed tests, sorry it took so long. Had a lot of other stuff to do =)

**Comment by NoahDragon** [comment]
LGTM. Thanks for contributing.

**Comment by jimmyn** [comment]
@NoahDragon could you update npm version please?

**Comment by NoahDragon** [comment]
@jimmyn I would like to, but only @tommy351 can update the npm package.

Currently, you could using `hexojs/hexo-generator-sitemap` in package.json to get the latest version.

**Pull request merged**
