### PR TITLE
feat: support IDN

### PR DESCRIPTION
**Pull request by curbengh**
Based on https://github.com/hexojs/hexo-generator-feed/pull/82, related issue https://github.com/hexojs/hexo-generator-feed/issues/63

### CODE REVIEW

**Comment by tomap** [comment]
I will test it on a sample site and merge :)

**Comment by tomap** [comment]
I tested with a site without IDN, but in that case, https://hexo-theme-minidyne-demo.netlify.com/sitemap.xml
it seems to work

**Comment by curbengh** [comment]
You can test locally and change the url.
My local test yields [sitemap.xml](https://github.com/hexojs/hexo-generator-sitemap/files/3490863/sitemap.xml.txt)

---

I just noticed this PR doesn't uriencode `root` value, even though it should. I'll update.
hexo-generator-feed may need to be updated as well.

**Comment by curbengh** [comment]
Superseded by https://github.com/hexojs/hexo-generator-sitemap/pull/66

**Pull request closed without merging**
